services:
  web:
    image: web-image
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    image: php-image
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network
  db:
    image: db-image
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_secret
    secrets: 
      - db_secret


secrets:
  db_secret:
    external: true

networks:
  app-network:
