services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
      - db
    networks:
      - app-network
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

networks:
  app-network:
